language: java
jdk: openjdk8
branches:
  only: master
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: OllLjkM9nNQgEtnW/Xmv5dWtHPBB6aP5/Ri7++Sh5AzqFoeGP2uLKefdT9WvWlT8jyFwU5k4WPkDjvAkPvtCUCsKC4ubIQ780vnlaIwvWgGBgr82DJmiUk3SJoWOVGmBykCdcc9u7dqA81y0zZssF2FDwwkFPZeApHgEe8ZVnzA=
  - secure: MwugML7PnmvrGY7I4ZQqxbX17wkjgzLiGSHvPcphsGWdFgpnDDLjzwDrhqfy0p79ajgVVZ8raPgqpmM4+5vWZnc81i3L/zmIr3aAHk+OVcGt/67dYU2tYaMW3TIxzghcK735UgNyqflX8NDvHuJAmeI0UVVwVXyKanRhF+AEAoo=
